### ISSUE TITLE
Advice session on 3nd May

### ISSUE THREAD

**Issue by 429AU** [jerry871002/ipsec-vpn#2]
## Routing
* Configure routing rules to ensure each site can only access the correct server
* Ensure correct source and destination addresses are used in IPsec tunnels

## Certificate Management Issues
* Design a certificate distribution mechanism to replace the current Vagrant method
* Consider using pre-shared key (PSK) authentication as an alternative to PKI certificates

## Scalability Issues
* Evaluate using containerized solutions to reduce costs per client
* Consider developing the service as a scalable web service for multi-client support
* Ensure persistent storage is correctly mapped from containers to corresponding devices

**Comment by jerry871002** [comment]
## Must do
Configure routing rules that the cloud gateway decides where the packet should go by source address (currently the server to go is hardcoded in the client site gateways)

## Full mark if we also do this
Containerize servers on the cloud and direct the traffic to the right server

## Bonus points
A realistic and feasible way to distribute certificates (currently it's `vagrant cp`)
